# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grafos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#editamos este archivo para la visualizacion

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1672, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(220, 50, 421, 151))
        self.tableWidget.setRowCount(4)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.btnPintarGrafo = QtWidgets.QPushButton(self.centralwidget)
        self.btnPintarGrafo.setGeometry(QtCore.QRect(390, 210, 101, 31))
        self.btnPintarGrafo.setObjectName("btnPintarGrafo")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(70, 260, 751, 491))
        self.graphicsView.setObjectName("graphicsView")
        self.lblTtitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo.setGeometry(QtCore.QRect(290, 10, 301, 31))
        self.lblTtitulo.setStyleSheet("font: bold 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(128, 0, 128);")  # Purple and bold
        self.lblTtitulo.setObjectName("lblTtitulo")
        self.lblTtitulo_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_3.setGeometry(QtCore.QRect(40, 90, 161, 31))
        self.lblTtitulo_3.setStyleSheet("font: bold 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(128, 0, 128);")  # Purple and bold
        self.lblTtitulo_3.setObjectName("lblTtitulo_3")
        self.lblTtitulo2 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo2.setGeometry(QtCore.QRect(80, 270, 181, 71))
        self.lblTtitulo2.setStyleSheet("font: bold 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(128, 0, 128);")  # Purple and bold
        self.lblTtitulo2.setText("")
        self.lblTtitulo2.setPixmap(QtGui.QPixmap("logo_eafit_blanco.png"))
        self.lblTtitulo2.setObjectName("lblTtitulo2")
        self.tablaAdyasencia = QtWidgets.QTableWidget(self.centralwidget)
        self.tablaAdyasencia.setGeometry(QtCore.QRect(890, 50, 421, 151))
        self.tablaAdyasencia.setRowCount(4)
        self.tablaAdyasencia.setColumnCount(4)
        self.tablaAdyasencia.setObjectName("tablaAdyasencia")
        self.tablak2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tablak2.setGeometry(QtCore.QRect(890, 290, 421, 151))
        self.tablak2.setRowCount(4)
        self.tablak2.setColumnCount(4)
        self.tablak2.setObjectName("tablak2")
        self.tablak3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tablak3.setGeometry(QtCore.QRect(890, 530, 421, 151))
        self.tablak3.setRowCount(4)
        self.tablak3.setColumnCount(4)
        self.tablak3.setObjectName("tablak3")
        self.btntablaAdyasencia = QtWidgets.QPushButton(self.centralwidget)
        self.btntablaAdyasencia.setGeometry(QtCore.QRect(1060, 210, 101, 31))
        self.btntablaAdyasencia.setObjectName("btntablaAdyasencia")
        self.btntablak2 = QtWidgets.QPushButton(self.centralwidget)
        self.btntablak2.setGeometry(QtCore.QRect(1060, 450, 101, 31))
        self.btntablak2.setObjectName("btntablak2")
        self.btntablak3 = QtWidgets.QPushButton(self.centralwidget)
        self.btntablak3.setGeometry(QtCore.QRect(1060, 690, 101, 31))
        self.btntablak3.setObjectName("btntablak3")
        self.lblTtitulo_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_2.setGeometry(QtCore.QRect(1020, 10, 181, 31))
        self.lblTtitulo_2.setStyleSheet("font: bold 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(128, 0, 128);")  # Purple and bold
        self.lblTtitulo_2.setObjectName("lblTtitulo_2")
        self.lblTtitulo_4 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_4.setGeometry(QtCore.QRect(1060, 250, 301, 31))
        self.lblTtitulo_4.setStyleSheet("font: bold 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(128, 0, 128);")  # Purple and bold
        self.lblTtitulo_4.setObjectName("lblTtitulo_4")
        self.lblTtitulo_5 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_5.setGeometry(QtCore.QRect(1070, 490, 301, 31))
        self.lblTtitulo_5.setStyleSheet("font: bold 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(128, 0, 128);")  # Purple and bold
        self.lblTtitulo_5.setObjectName("lblTtitulo_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1672, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.btnPintarGrafo.setText(_translate("MainWindow", "Dibujar Grafo"))
        self.lblTtitulo.setText(_translate("MainWindow", "Grafos por Valentina Castro"))
        self.lblTtitulo_3.setText(_translate("MainWindow", "Matriz de Pesos>>"))
        self.tablaAdyasencia.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.tablak2.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.tablak3.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.btntablaAdyasencia.setText(_translate("MainWindow", "GENERAR"))
        self.btntablak2.setText(_translate("MainWindow", "GENERAR"))
        self.btntablak3.setText(_translate("MainWindow", "GENERAR "))
        self.lblTtitulo_2.setText(_translate("MainWindow", "TABLA ADYACENCIA"))
        self.lblTtitulo_4.setText(_translate("MainWindow", "TABLA K2"))
        self.lblTtitulo_5.setText(_translate("MainWindow", "TABLA K3"))
