# -*- coding: utf-8 -*-
# This specifies the file encoding as UTF-8 to handle special characters properly.

# Form implementation generated from reading ui file 'grafos.ui'
# Generated using PyQt5's UI designer tool (pyuic5).

# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.

# Import necessary PyQt5 modules
from PyQt5 import QtCore, QtGui, QtWidgets

# Define the class that sets up the UI for the main application window
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Set up the main window's properties
        MainWindow.setObjectName("MainWindow")  # Name for the main window
        MainWindow.resize(932, 798)  # Set dimensions for the window

        # Create the central widget, which is the main area of the UI
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Add a table widget for displaying data
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(220, 50, 421, 151))  # Set position and size
        self.tableWidget.setRowCount(4)  # Set number of rows
        self.tableWidget.setColumnCount(4)  # Set number of columns
        self.tableWidget.setObjectName("tableWidget")

        # Add a button to draw the graph
        self.btnPintarGrafo = QtWidgets.QPushButton(self.centralwidget)
        self.btnPintarGrafo.setGeometry(QtCore.QRect(390, 210, 101, 31))  # Set position and size
        self.btnPintarGrafo.setObjectName("btnPintarGrafo")

        # Add a graphics view widget to visualize the graph
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(70, 260, 751, 491))  # Set position and size
        self.graphicsView.setObjectName("graphicsView")

        # Add a label with a title
        self.lblTtitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo.setGeometry(QtCore.QRect(290, 10, 301, 31))  # Set position and size
        self.lblTtitulo.setStyleSheet("font: bold 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(128, 0, 128);")  # Apply style: bold and purple font
        self.lblTtitulo.setObjectName("lblTtitulo")

        # Add another label for a subtitle or section description
        self.lblTtitulo_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_3.setGeometry(QtCore.QRect(40, 90, 161, 31))  # Set position and size
        self.lblTtitulo_3.setStyleSheet("font: bold 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(128, 0, 128);")  # Apply style: bold and purple font
        self.lblTtitulo_3.setObjectName("lblTtitulo_3")

        # Add a label to display an image
        self.lblTtitulo2 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo2.setGeometry(QtCore.QRect(80, 270, 181, 71))  # Set position and size
        self.lblTtitulo2.setStyleSheet("font: bold 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(128, 0, 128);")  # Apply style: bold and purple font
        self.lblTtitulo2.setText("")  # Clear initial text
        self.lblTtitulo2.setPixmap(QtGui.QPixmap("logo_eafit_blanco.png"))  # Load an image
        self.lblTtitulo2.setObjectName("lblTtitulo2")

        # Add another table widget for the adjacency matrix
        self.tablaAdyasencia = QtWidgets.QTableWidget(self.centralwidget)
        self.tablaAdyasencia.setGeometry(QtCore.QRect(890, 50, 421, 151))  # Set position and size
        self.tablaAdyasencia.setRowCount(4)  # Set number of rows
        self.tablaAdyasencia.setColumnCount(4)  # Set number of columns
        self.tablaAdyasencia.setObjectName("tablaAdyasencia")

        # Add a table widget for the K2 matrix
        self.tablak2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tablak2.setGeometry(QtCore.QRect(890, 290, 421, 151))  # Set position and size
        self.tablak2.setRowCount(4)  # Set number of rows
        self.tablak2.setColumnCount(4)  # Set number of columns
        self.tablak2.setObjectName("tablak2")

        # Add a table widget for the K3 matrix
        self.tablak3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tablak3.setGeometry(QtCore.QRect(890, 530, 421, 151))  # Set position and size
        self.tablak3.setRowCount(4)  # Set number of rows
        self.tablak3.setColumnCount(4)  # Set number of columns
        self.tablak3.setObjectName("tablak3")

        # Add a button for generating the adjacency matrix
        self.btntablaAdyasencia = QtWidgets.QPushButton(self.centralwidget)
        self.btntablaAdyasencia.setGeometry(QtCore.QRect(1060, 210, 101, 31))  # Set position and size
        self.btntablaAdyasencia.setObjectName("btntablaAdyasencia")

        # Add a button for generating the K2 matrix
        self.btntablak2 = QtWidgets.QPushButton(self.centralwidget)
        self.btntablak2.setGeometry(QtCore.QRect(1060, 450, 101, 31))  # Set position and size
        self.btntablak2.setObjectName("btntablak2")

        # Add a button for generating the K3 matrix
        self.btntablak3 = QtWidgets.QPushButton(self.centralwidget)
        self.btntablak3.setGeometry(QtCore.QRect(1060, 690, 101, 31))  # Set position and size
        self.btntablak3.setObjectName("btntablak3")

        # Add a label for the adjacency table section
        self.lblTtitulo_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_2.setGeometry(QtCore.QRect(900, 10, 300, 31))  # Set position and size
        self.lblTtitulo_2.setStyleSheet("font: bold 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(128, 0, 128);")  # Apply style: bold and purple font
        self.lblTtitulo_2.setObjectName("lblTtitulo_2")

        # Add labels for the K2 and K3 matrix sections
        self.lblTtitulo_4 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_4.setGeometry(QtCore.QRect(900, 250, 301, 31))  # Set position and size
        self.lblTtitulo_4.setStyleSheet("font: bold 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(128, 0, 128);")  # Apply style: bold and purple font
        self.lblTtitulo_4.setObjectName("lblTtitulo_4")

        self.lblTtitulo_5 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_5.setGeometry(QtCore.QRect(900, 490, 301, 31))  # Set position and size
        self.lblTtitulo_5.setStyleSheet("font: bold 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(128, 0, 128);")  # Apply style: bold and purple font
        self.lblTtitulo_5.setObjectName("lblTtitulo_5")

        # Set the central widget for the main window
        MainWindow.setCentralWidget(self.centralwidget)

        # Create a menu bar (currently unused)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1672, 21))  # Set position and size
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        # Create a status bar (currently unused)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Retranslate the UI for setting dynamic text
        self.retranslateUi(MainWindow)

        # Connect signals and slots (e.g., button clicks)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        # Function to set dynamic text for widgets
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.btnPintarGrafo.setText(_translate("MainWindow", "Dibujar Grafo"))
        self.lblTtitulo.setText(_translate("MainWindow", "Grafos por Valentina Castro"))
        self.lblTtitulo_3.setText(_translate("MainWindow", "Matriz de Pesos"))
        self.tablaAdyasencia.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.tablak2.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.tablak3.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.btntablaAdyasencia.setText(_translate("MainWindow", "GENERAR"))
        self.btntablak2.setText(_translate("MainWindow", "GENERAR"))
        self.btntablak3.setText(_translate("MainWindow", "GENERAR "))
        self.lblTtitulo_2.setText(_translate("MainWindow", "TABLA ADYACENCIA"))
        self.lblTtitulo_4.setText(_translate("MainWindow", "TABLA K=2"))
        self.lblTtitulo_5.setText(_translate("MainWindow", "TABLA K=3"))
